### ISSUE TITLE
Integrate tools within FLEA pipeline into Galaxy

### ISSUE THREAD

**Issue by stevenweaver** [veg/tools-iuc#41]
We will need to integrate all tools associated with FLEA into Galaxy. The repository is located [here](https://github.com/veg/flea-pipeline). The pipeline utilizes a workflow language called [nextflow](https://www.nextflow.io/). Documentation should already be thorough, but utilizing [nextflow's tracing and visualization](https://www.nextflow.io/docs/latest/tracing.html?highlight=dag#execution-report) may aid in determining each step in the process.

**Comment by stephenshank** [comment]
[A link to the FLEA biorxiv paper.](https://www.biorxiv.org/content/early/2017/12/07/230474)
