### ISSUE TITLE
Wrap `hivnetworkcsv` which is a Python library with some funky dependancies

### ISSUE THREAD

**Issue by stevenweaver** [veg/tools-iuc#5]
https://github.com/veg/hivclustering 

(look at the develop branch)

Input (at least CSV file from TN93) => JSON file with the inferred network + some states.

**Comment by davebx** [comment]
I've started work on this, feel free to assign me at your leisure.

**Comment by davebx** [comment]
First pass wrapper is at https://github.com/davebx/tools-iuc/tree/hivclustering/tools/hivclustering, expect updates

**Comment by stevenweaver** [comment]
@davebx, 

Very cool. Feel free to open a PR if you like. We're actively installing the tools and testing them out on galaxy.hyphy.org.

Best,
Steven

**Comment by davebx** [comment]
This was completed in #11

**Comment by davebx** [comment]
Empty comment to test gitter webhook
