### ISSUE TITLE
Adapt Swanstrom Lab's primer ID error detection model for use with NGS pipeline

### ISSUE THREAD

**Issue by stevenweaver** [veg/tools-iuc#7]
According to the [Swanstrom Lab](http://jvi.asm.org/content/89/16/8540.full.pdf+html)

> Primer IDs that appeared once came from sequence reads that on average had significantly lower quality scores than the scores for the higher frequency reads. This observation suggests that low-abundance Primer ID reads are at least in part the result of misreading of more-abundant Primer IDs that are being resampled (after the PCR amplification step) in the sequencing.

Ruby scripts for the simulation model, consensus cutoff, and consensus creation are provided as supplementary materials in the paper. 

We will need to implement the error model in a new script for use with the rest of our pipeline.

**Comment by spond** [comment]
Dear @stevenweaver,

Which language would be preferable? I can always do a C/C++ tool based on the TN93 codebase.

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @spond, 

A C/C++ tool would be ideal.

Best,
Steven

**Comment by spond** [comment]
Dear @stevenweaver,

You got it. Will examine the Ruby code and the manuscript and see what I can do. Fun side-project.

Best,
Sergei
